
server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    username: root
    password: 'Iatgoat#23@2022'
#    password: 'Iatgoat#23'
    url: jdbc:mysql://127.0.0.1:3306/liquor_plug?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowLoadLocalInfile=true
#    url: jdbc:mysql://liquorplug-db.cnigdd0ibalf.us-west-1.rds.amazonaws.com/liquor_plug?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowLoadLocalInfile=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 400
      idle-timeout: 30000
      minimum-idle: 20
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: kevindzinde2@gmail.com
    password: pdwyeschpdnhwijo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwt:
    secret: 'qwerty123'
    expiration-in-ms: 86400000
authentication:
  internal-api-key: 'InternalApiKey1234!'
